### ISSUE TITLE
Consider turning some stores into statics rather than passing them around within contexts

### ISSUE THREAD

**Issue by feds01** [hash-org/hashc#816]
Things to do:

- [x] Add a static STORES variable (#872)
- [x] Traits for accessing store data through IDs without a special context (#872)
- [x] Implement display for TIR IDs without a special context (#882)
- [ ] Remove `stores` from the TIR environment and solely use the static version. (will be done separately)
